/* CyberSutra is intentionally mock-only. Evidence text is always rendered with textContent. */
const KEY = 'cybersutra.mock.case.v1';
const MAX_BYTES = 5 * 1024 * 1024;
const ACCEPTED = new Set(['image/png','image/jpeg','application/pdf','text/plain']);
const STEPS = ['Describe','Evidence','Timeline','Review','Readiness','Report','Acknowledgement'];
const required = ['incident_description','transaction_amount','transaction_timestamp','transaction_id','payment_institution'];
const $ = (s, root=document) => root.querySelector(s);
const id = (p) => `${p}_${crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2)}`;
// All interpolated user/evidence values pass through this before entering HTML.
// Uploaded content never becomes executable markup or application instructions.
const escapeText = (v) => String(v ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
function cleanFilename(name){ return name.replace(/[^a-zA-Z0-9._ -]/g, '_').replace(/^\.+/, '').slice(0, 120) || 'evidence'; }
function newCase(){ return {id:id('case'), description:'', evidence:[], facts:[], events:[], contradictions:[], submitted:false, acknowledgement:null}; }
let state = load() || null;
function load(){ try { const raw=localStorage.getItem(KEY); return raw ? JSON.parse(raw) : null; } catch { return null; } }
function save(){ if(state) localStorage.setItem(KEY, JSON.stringify(state)); }
function fact(field,value,evidenceId,sourceReference,confidence=.9,status='needs_confirmation'){ return {id:id('fact'),field,value:String(value),evidenceId,sourceReference,confidence,status,userConfirmed:false}; }
function demoCase(){ const c=newCase(); c.description='I received messages asking me to complete KYC verification and paid a requested fee.'; c.evidence=[
 {id:'ev_message',type:'WhatsApp screenshot',filename:'whatsapp_kyc_demo.png',mimeType:'image/png',size:182000,source:'Synthetic demo',hash:'demo-message',processingStatus:'processed'},
 {id:'ev_receipt',type:'Bank receipt',filename:'receipt_demo.pdf',mimeType:'application/pdf',size:94000,source:'Synthetic demo',hash:'demo-receipt',processingStatus:'processed'},
 {id:'ev_sms',type:'SMS',filename:'sms_demo.txt',mimeType:'text/plain',size:310,source:'Synthetic demo',hash:'demo-sms',processingStatus:'processed'}];
 c.facts=[fact('phone_number','+91 90000 12345','ev_message','WhatsApp screenshot / contact header',.96),fact('suspicious_url','https://verify-kyc.example/secure','ev_message','WhatsApp screenshot / message text',.93),fact('transaction_amount','18500','ev_receipt','Bank receipt / amount',.99),fact('transaction_timestamp','2026-08-25T14:08','ev_receipt','Bank receipt / timestamp',.98),fact('transaction_id','DEMO-UTR-482916','ev_receipt','Bank receipt / reference number',.99),fact('payment_institution','Demo Bank','ev_receipt','Bank receipt / institution',.97),fact('transaction_amount','15500','ev_sms','SMS / message text',.82)];
 c.events=[{id:id('event'),timestamp:'2026-08-25T14:02',description:'Contact initiated a KYC verification conversation.',evidenceIds:['ev_message'],confidence:.92,userConfirmed:false},{id:id('event'),timestamp:'2026-08-25T14:05',description:'A payment was requested through a suspicious link.',evidenceIds:['ev_message'],confidence:.9,userConfirmed:false},{id:id('event'),timestamp:'2026-08-25T14:08',description:'A transaction receipt records a payment.',evidenceIds:['ev_receipt'],confidence:.98,userConfirmed:false}]; derive(c); return c; }
function derive(c){ const groups={}; c.facts.forEach(f=>{if(f.value) (groups[f.field]??=[]).push(f)}); c.contradictions=Object.entries(groups).flatMap(([field,fs])=>{const vals=[...new Set(fs.map(f=>f.value.trim().toLowerCase()))];return vals.length>1?[{id:`conflict_${field}`,field,values:fs.map(f=>f.value),evidenceIds:fs.map(f=>f.evidenceId),severity:['transaction_amount','transaction_id','transaction_timestamp'].includes(field)?'critical':'important',status:'unresolved',resolution:null}]:[]}); }
function readiness(c){ const fields=new Set(c.facts.filter(f=>f.value).map(f=>f.field)); const missing=required.filter(x=>x!=='incident_description'&&!fields.has(x)); if(!c.description.trim())missing.unshift('incident_description'); const critical=c.contradictions.some(x=>x.severity==='critical'&&x.status==='unresolved'); const uncertain=c.facts.some(f=>f.status==='needs_confirmation'&&!f.userConfirmed); return {state:missing.length?'INCOMPLETE':critical?'NEEDS_REVIEW':uncertain?'NEEDS_REVIEW':'READY',missing,critical,uncertain}; }
function progress(active){return `<nav class="progress" aria-label="Case progress">${STEPS.map((x,i)=>`<span class="${i===active?'current':i<active?'done':''}">${i+1}. ${x}</span>`).join('')}</nav>`}
function render(){ const app=$('#app'); if(!state){app.innerHTML='';app.append($('#landing-template').content.cloneNode(true));return;} const page=location.hash.slice(1)||'describe'; const views={describe, evidence, timeline, review, readinessView, report, acknowledgement}; app.innerHTML=views[page]?views[page]():describe(); bind(); }
function describe(){return `${progress(0)}<h1 class="page-title">Tell us what happened</h1><p class="subtle">Use your own words. This description is not treated as evidence until you confirm it in the report.</p><form id="descriptionForm" class="card"><div class="field"><label for="description">What happened?</label><textarea id="description" required maxlength="3000" placeholder="For example: I received a message asking me to verify my KYC and was asked to make a payment.">${escapeText(state.description)}</textarea></div><div class="step-actions"><button class="primary">Save and continue</button></div></form>`}
function evidence(){return `${progress(1)}<h1 class="page-title">Add your evidence</h1><p class="subtle">Files stay in this browser for the mock demo. Files are validated before being listed; they are never executed or fetched.</p><div class="card upload"><label for="file">Choose PNG, JPEG, PDF or text file (up to 5 MB)</label><input id="file" type="file" accept="image/png,image/jpeg,application/pdf,text/plain" /><p id="uploadError" class="error hidden" role="alert"></p></div><div class="card"><h2>Evidence locker</h2>${state.evidence.length?state.evidence.map(e=>`<div class="item"><div><strong>${escapeText(e.filename)}</strong><p>${escapeText(e.type)} · ${Math.round(e.size/1024)} KB · <span class="status ready">${escapeText(e.processingStatus)}</span></p></div><button class="secondary" data-remove="${e.id}">Remove</button></div>`).join(''):'<p class="subtle">No evidence added yet. You can still enter information manually in review.</p>'}</div><div class="step-actions"><a class="secondary" href="#describe">Back</a><a class="primary" href="#timeline">Continue to timeline</a></div>`}
function timeline(){const events=[...state.events].sort((a,b)=>a.timestamp.localeCompare(b.timestamp));return `${progress(2)}<h1 class="page-title">Timeline</h1><p class="subtle">These are candidate events derived from your evidence. Confirming them makes their status explicit.</p><div class="card timeline">${events.length?events.map(e=>`<article><strong>${new Date(e.timestamp).toLocaleString()}</strong><p>${escapeText(e.description)}</p><small>Source: ${e.evidenceIds.map(x=>escapeText(state.evidence.find(e=>e.id===x)?.filename||x)).join(', ')} · ${Math.round(e.confidence*100)}% confidence</small></article>`).join(''):'<p class="subtle">No timestamped evidence is available yet.</p>'}</div><div class="step-actions"><a class="secondary" href="#evidence">Back</a><a class="primary" href="#review">Review extracted details</a></div>`}
function review(){return `${progress(3)}<h1 class="page-title">Review the details</h1><p class="subtle">Each value retains a link to its source. Confirm only details you believe are correct.</p><div class="card"><table class="facts"><thead><tr><th>Field</th><th>Value</th><th>Evidence source</th><th>Status</th></tr></thead><tbody>${state.facts.map(f=>`<tr><td>${escapeText(f.field.replaceAll('_',' '))}</td><td>${escapeText(f.value)}</td><td><button class="source" data-source="${f.evidenceId}">${escapeText(f.sourceReference)}</button></td><td><label><input type="checkbox" data-confirm="${f.id}" ${f.userConfirmed?'checked':''}/> Confirm</label></td></tr>`).join('')}</tbody></table></div><div class="card"><h2>Add a detail manually</h2><form id="factForm" class="grid"><div class="field"><label>Field <select id="factField"><option value="transaction_amount">Transaction amount</option><option value="transaction_id">Transaction ID</option><option value="transaction_timestamp">Transaction time</option><option value="payment_institution">Payment institution</option><option value="phone_number">Phone number</option></select></label></div><div class="field"><label>Value <input id="factValue" maxlength="160" required /></label></div><div class="field"><label>Why / source <input id="factSource" maxlength="160" value="Entered by user" required /></label></div><div class="field"><button class="secondary">Add detail</button></div></form></div><div class="step-actions"><a class="secondary" href="#timeline">Back</a><a class="primary" href="#readiness">Check readiness</a></div>`}
function readinessView(){const r=readiness(state);return `${progress(4)}<h1 class="page-title">Report readiness</h1><div class="card"><span class="status ${r.state==='READY'?'ready':r.state==='INCOMPLETE'?'danger':'warning'}">${r.state}</span><h2>${r.state==='READY'?'Ready for your review':r.state==='INCOMPLETE'?'More critical information is needed':'Review required before the report'}</h2>${r.missing.length?`<div class="error"><strong>Missing critical information:</strong> ${r.missing.map(x=>escapeText(x.replaceAll('_',' '))).join(', ')}.</div>`:''}${r.critical?`<div class="error"><strong>Unresolved contradictions:</strong> the values conflict across evidence. CyberSutra will not choose one for you.</div>`:''}${r.uncertain?`<div class="callout"><strong>Unconfirmed details:</strong> review each source-linked value before relying on this summary.</div>`:''}<p class="subtle">This state is calculated by explicit rules; it is not an acceptance prediction.</p></div>${state.contradictions.length?`<div class="card"><h2>Contradictions</h2>${state.contradictions.map(c=>`<div class="item"><div><strong>${escapeText(c.field.replaceAll('_',' '))} mismatch</strong><p>Evidence values: ${c.values.map(escapeText).join(' vs ')}.</p></div><button class="secondary" data-resolve="${c.id}">${c.status==='resolved'?'Resolved':'Mark reviewed'}</button></div>`).join('')}</div>`:''}<div class="step-actions"><a class="secondary" href="#review">Back</a><a class="primary" href="#report">Review report</a></div>`}
function report(){const r=readiness(state);return `${progress(5)}<h1 class="page-title">Report review</h1><div class="notice"><strong>Mock report only.</strong> This is not an official filing and does not contact NCRP or any government system.</div><article class="card"><h2>Financial cyber fraud — draft</h2><p>${escapeText(state.description||'No incident description provided.')}</p><h3>Evidence-linked details</h3>${state.facts.length?`<ul>${state.facts.map(f=>`<li>${escapeText(f.field.replaceAll('_',' '))}: ${escapeText(f.value)} <small>(source: ${escapeText(f.sourceReference)})</small></li>`).join('')}</ul>`:'<p>No details added.</p>'}<h3>Readiness</h3><p><span class="status ${r.state==='READY'?'ready':'warning'}">${r.state}</span></p></article><div class="step-actions"><a class="secondary" href="#readiness">Back</a><button class="primary" data-action="submit" ${r.state==='INCOMPLETE'?'disabled':''}>Submit mock report</button></div>`}
function acknowledgement(){return `${progress(6)}<h1 class="page-title">Mock acknowledgement</h1><div class="success"><h2>Mock report recorded</h2><p>Your local demo acknowledgement is <strong>${escapeText(state.acknowledgement||'not available')}</strong>.</p><p>No data was sent outside this browser. This acknowledgement is not valid for a real complaint.</p></div><div class="step-actions"><button class="primary" data-action="new-case">Start another incident</button></div>`}
function bind(){ const form=$('#descriptionForm'); if(form)form.onsubmit=e=>{e.preventDefault();state.description=$('#description').value.trim();save();location.hash='evidence';}; const input=$('#file');if(input)input.onchange=handleUpload; document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.evidence=state.evidence.filter(e=>e.id!==b.dataset.remove);state.facts=state.facts.filter(f=>f.evidenceId!==b.dataset.remove);derive(state);save();render();});document.querySelectorAll('[data-confirm]').forEach(x=>x.onchange=()=>{const f=state.facts.find(f=>f.id===x.dataset.confirm);f.userConfirmed=x.checked;save();});document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>alert(`Source evidence: ${state.evidence.find(e=>e.id===b.dataset.source)?.filename||'Manual entry'}\n\n${state.facts.find(f=>f.evidenceId===b.dataset.source)?.sourceReference||''}`)); const ff=$('#factForm');if(ff)ff.onsubmit=e=>{e.preventDefault();state.facts.push(fact($('#factField').value,$('#factValue').value.trim(),null,$('#factSource').value.trim(),1,'user_entered'));derive(state);save();render();};document.querySelectorAll('[data-resolve]').forEach(b=>b.onclick=()=>{const c=state.contradictions.find(c=>c.id===b.dataset.resolve);c.status='resolved';c.resolution='Reviewed by user';save();render();});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{if(b.dataset.action==='new-case'){state=newCase();save();location.hash='describe';}if(b.dataset.action==='load-demo'){state=demoCase();save();location.hash='evidence';}if(b.dataset.action==='submit'){state.submitted=true;state.acknowledgement=`MOCK-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;save();location.hash='acknowledgement';}});}
function handleUpload(e){const file=e.target.files[0], box=$('#uploadError');if(!file)return;const fail=m=>{box.textContent=m;box.classList.remove('hidden');e.target.value='';};if(file.size>MAX_BYTES)return fail('This file is larger than the 5 MB demo limit.');if(!ACCEPTED.has(file.type))return fail('This file type is not supported. Use PNG, JPEG, PDF, or plain text.');const ev={id:id('ev'),type:file.type==='application/pdf'?'Document':file.type==='text/plain'?'Text message':'Screenshot',filename:cleanFilename(file.name),mimeType:file.type,size:file.size,source:'User upload',hash:`local-${file.size}-${file.lastModified}`,processingStatus:'stored; extraction unavailable'};state.evidence.push(ev);save();render();}
window.addEventListener('hashchange',render);$('#resetCase').onclick=()=>{localStorage.removeItem(KEY);state=null;location.hash='start';render();};render();
